"""added stima table

Revision ID: eecf32dfda50
Revises: 
Create Date: 2023-11-06 23:24:32.005918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eecf32dfda50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stimas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=255), nullable=False),
    sa.Column('bill', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stimas')
    # ### end Alembic commands ###
